name: Build Artifact 🏗️
on:
  push:
    tags:
      - 'v*' # This will trigger the workflow on any tag that starts with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r ./requirements.txt
          pip install pyinstaller
          pyinstaller ./gemini-cli.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: gemini-cli
          retention-days: 1
          path: dist/gemini-cli

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gemini-cli

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          fail_if_no_release: false
          files: dist/gemini-cli
          tag_name: ${{ github.ref }}
          name: ${{ github.event.inputs.releaseName }}
          token: ${{ secrets.ACCOUNT_TOKEN }}
